#!/usr/bin/python
"""
Usage:

In a terminal/command line, cd to the directory where this file lives. Then...

With embedded urls: ( download the hardcoded list of files in the 'files =' block below)

    python ./download-all-2026-06-06_12-22-55.py

Download all files in a Metalink/CSV: (downloaded from ASF Vertex)

    python ./download-all-2026-06-06_12-22-55.py /path/to/downloads.metalink localmetalink.metalink localcsv.csv

Compatibility: python >= 3.6

If downloading from a trusted source with invalid SSL Certs, use --insecure to ignore

For more information on bulk downloads, navigate to:
    https://asf.alaska.edu/how-to/data-tools/data-tools/#bulk_download

This script was generated by the Alaska Satellite Facility's bulk download service.
For more information on the service, navigate to:
    http://bulk-download.asf.alaska.edu/help
"""


import sys
import csv
import os
import os.path
import tempfile
import shutil
import re

import base64
import time
import getpass
import ssl
import signal
import socket

from urllib.parse import urlparse
import xml.etree.ElementTree as ET

from urllib.request import build_opener, install_opener, Request, urlopen
from urllib.request import HTTPHandler, HTTPSHandler, HTTPCookieProcessor
from urllib.error import HTTPError, URLError

from http.cookiejar import MozillaCookieJar
from io import StringIO

###
# Global variables intended for cross-thread modification
abort = False


###
# A routine that handles trapped signals
def signal_handler(sig, frame):
    global abort
    sys.stderr.output("\n > Caught Signal. Exiting!\n")
    abort = True  # necessary to cause the program to stop
    raise SystemExit  # this will only abort the thread that the ctrl+c was caught in


class bulk_downloader:
    def __init__(self):
        # List of files to download
        self.files = [ "https://d3gm2hf49xd6jj.cloudfront.net/dd80062e-2879-4678-81db-f3f38e203fe0/S1_021606_IW3_20211222_20211228_VV_INT80_3E6A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/994f349d-236e-42e9-a784-8582801f5a03/S1_021606_IW3_20211005_20211017_VV_INT80_F7DC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/df6576f0-4367-4ccd-8ed6-fb74b7a921c9/S1_021606_IW3_20211204_20211222_VV_INT80_37EC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/67bdb68f-0995-4170-afcf-6c6f627a15e9/S1_021606_IW3_20211204_20211216_VV_INT80_A858.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/d1439430-16d7-4147-9d1e-ad4e8a6881b1/S1_021606_IW3_20211122_20211216_VV_INT80_41A9.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/7f401896-96b4-4bd5-bd49-f98a8439530a/S1_021606_IW3_20211005_20211029_VV_INT80_7726.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/06f057d9-c40b-4b24-bd30-c8992470c144/S1_021606_IW3_20211017_20211110_VV_INT80_8F73.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/90680785-e544-46bd-81d6-c9f39a775c67/S1_021606_IW3_20211204_20211228_VV_INT80_9E1D.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/6a095338-db34-4f06-ba35-5635bc163389/S1_021606_IW3_20211216_20211222_VV_INT80_4B0E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/664ff8e7-8e87-4163-9d66-7a7a1bd57919/S1_021606_IW3_20211029_20211122_VV_INT80_23CB.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b7148b2d-3ada-4341-b975-4cd753975d4b/S1_021606_IW3_20211029_20211110_VV_INT80_959D.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/e048a33e-ecf0-4fd8-9e8c-4bb6ae984ccd/S1_021606_IW3_20211017_20211029_VV_INT80_12C5.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/cfb4c818-8901-4a2b-bf83-b1512e46da04/S1_021606_IW3_20211110_20211122_VV_INT80_0682.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/1302244c-cd9e-4055-b148-0fe472c17915/S1_021606_IW3_20210923_20211017_VV_INT80_B002.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/3884fab1-f782-4bb1-a043-bbc94ebfa1e9/S1_021606_IW3_20211216_20211228_VV_INT80_E1B1.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/0c0fe07c-48a5-47bc-9093-ee03b71de279/S1_021606_IW3_20211110_20211204_VV_INT80_4A28.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4348505f-1661-4e53-ae6b-1d37039fe83a/S1_021606_IW3_20211122_20211204_VV_INT80_8784.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/69c2554d-8a06-47e7-b437-8cda27fea55f/S1_021606_IW3_20210607_20210701_VV_INT80_0146.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/63b016db-f70e-4ca2-88c8-505d4b9daf1f/S1_021606_IW3_20210701_20210725_VV_INT80_2F22.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4928e2b3-ffe9-47ff-ad4b-4004bed16652/S1_021606_IW3_20210713_20210725_VV_INT80_0B09.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/89e822b8-4e89-41cf-ba54-90fdd0d21a6c/S1_021606_IW3_20210818_20210830_VV_INT80_037F.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/158e6f0e-381e-4b57-a556-12fcb6ca8e72/S1_021606_IW3_20210619_20210701_VV_INT80_9F1E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/78c001d6-280c-4017-85ce-f280b63d1339/S1_021606_IW3_20210806_20210818_VV_INT80_AA42.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b968a16c-ce05-4e8a-b963-6cd7fe98bd5f/S1_021606_IW3_20210923_20211005_VV_INT80_2C1A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/d2512f0c-9d39-4fc1-b717-6aeb24ac9b98/S1_021606_IW3_20210806_20210830_VV_INT80_8E69.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/46e8dce7-048e-4b0e-b287-b7175321d87d/S1_021606_IW3_20210911_20211005_VV_INT80_0E92.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/db06900f-9374-4dd6-8572-0232c04947ef/S1_021606_IW3_20210701_20210713_VV_INT80_52D6.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/01df7e6e-3dc1-4a29-b2b9-2d487e0ecb82/S1_021606_IW3_20210818_20210911_VV_INT80_A20D.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/1dbc0fe2-d314-4d83-a0f0-52504a8fd043/S1_021606_IW3_20210830_20210911_VV_INT80_4D20.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/bc6e1fe1-874b-4777-8fc7-ba95c6922f21/S1_021606_IW3_20210619_20210713_VV_INT80_F10D.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4f1c0a6d-76dd-4e63-bc25-1b71b03b3655/S1_021606_IW3_20210911_20210923_VV_INT80_C9FB.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/a75eb944-9b80-4ddc-9d43-5cb20a4a99b7/S1_021606_IW3_20210830_20210923_VV_INT80_A8A7.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/825f8ad7-c8a3-4101-9f24-aec63f35fe54/S1_021606_IW3_20210526_20210619_VV_INT80_40FB.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/f5fd7144-8484-433d-b925-83234037ba0d/S1_021606_IW3_20210713_20210806_VV_INT80_D8CD.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/49245cdb-a785-4b05-bfb1-417fddf43db4/S1_021606_IW3_20210607_20210619_VV_INT80_B050.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/115395e8-9dd5-425c-8b27-e2897c952676/S1_021606_IW3_20210725_20210806_VV_INT80_4488.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/da06c8a0-47e1-4f50-9510-cfbef8ca80f6/S1_021606_IW3_20210725_20210818_VV_INT80_36EC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/2091705a-a818-47a8-86e6-d545a66d92ea/S1_021606_IW3_20210102_20210126_VV_INT80_E24E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/79ebda95-da8f-4673-933a-d2840f98626d/S1_021606_IW3_20201010_20201103_VV_INT80_F8F7.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/04fc7112-cc76-4373-bd9e-103d08407d67/S1_021606_IW3_20210219_20210303_VV_INT80_3823.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/a744ee7a-e518-4764-877e-10521e65eb01/S1_021606_IW3_20201103_20201127_VV_INT80_5FA1.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/2dca7bf6-0fb5-478f-a136-8568e4426d2c/S1_021606_IW3_20201209_20201221_VV_INT80_B1CF.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/ac7560f7-d280-484c-a747-722df5880ebf/S1_021606_IW3_20201103_20201115_VV_INT80_D9C1.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/758ca348-1abc-4e33-8f39-6488be32a15e/S1_021606_IW3_20201115_20201127_VV_INT80_ED1D.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/26b6c40c-2261-438e-8504-6f67a00c873c/S1_021606_IW3_20210126_20210219_VV_INT80_053A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/fabb6d4f-fbf1-4bf4-a5c3-b590a2cfa678/S1_021606_IW3_20210303_20210327_VV_INT80_69D2.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/527a9ded-67cb-44bd-90ed-6a2a46b058f3/S1_021606_IW3_20210315_20210327_VV_INT80_6656.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/81fd364d-4213-4145-8bfc-316c75e7772c/S1_021606_IW3_20210126_20210207_VV_INT80_8190.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/910a84ff-18d3-4bf7-9b4a-2cd87a5bc019/S1_021606_IW3_20201010_20201022_VV_INT80_2C35.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/eaa01b65-dc52-4f51-93b8-cfe914cc3ca8/S1_021606_IW3_20201115_20201209_VV_INT80_A525.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/cba1d000-eecf-4308-b156-76672949a5bd/S1_021606_IW3_20210114_20210207_VV_INT80_B8DC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/a962cfce-1dea-4ceb-9f41-1a20e5e9bcf2/S1_021606_IW3_20201221_20210102_VV_INT80_B223.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4f8c265e-0685-480e-8e7a-e750ba02135f/S1_021606_IW3_20201127_20201209_VV_INT80_AA92.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4c290f09-c0e5-45bc-bda1-67db5be3143b/S1_021606_IW3_20210327_20210420_VV_INT80_0727.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/5949028b-aa19-40fb-ad78-cdf98e585890/S1_021606_IW3_20210102_20210114_VV_INT80_3770.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/c6f90c95-b996-412e-923a-84c5b44abf9a/S1_021606_IW3_20210207_20210219_VV_INT80_2030.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/6117e724-e406-4822-8210-dd88191ac16d/S1_021606_IW3_20210420_20210502_VV_INT80_E306.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/60f4b090-9a1c-4d22-9aa3-975b36257c2a/S1_021606_IW3_20210315_20210408_VV_INT80_A9EC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/ca095879-3a51-43d7-9bee-974b0a87b08d/S1_021606_IW3_20210303_20210315_VV_INT80_ABB6.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b58f8f0c-d855-496c-81fe-5ed3ac460dc0/S1_021606_IW3_20201127_20201221_VV_INT80_2DB3.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/7a934fb2-4e15-460f-b686-dad3a901246b/S1_021606_IW3_20210514_20210607_VV_INT80_420B.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/156911ee-b2b2-4b34-9dc6-d0c7e095492c/S1_021606_IW3_20210219_20210315_VV_INT80_A2C8.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b78687cd-8f0e-4338-a3da-1122f2299968/S1_021606_IW3_20210502_20210514_VV_INT80_5969.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/96e48cf0-4e19-413e-9476-8c45d8bae9ba/S1_021606_IW3_20210526_20210607_VV_INT80_A8DE.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/6b3f55f9-a823-464c-9db0-265aab66cb3c/S1_021606_IW3_20201022_20201103_VV_INT80_CA5E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4a498312-320a-4ab5-8e9a-7e3cbf03cc6b/S1_021606_IW3_20210502_20210526_VV_INT80_81B1.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/00678f61-a1c2-4f0e-9323-25c9971732e0/S1_021606_IW3_20201022_20201115_VV_INT80_5F30.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/df0e8cf4-b94e-4ec6-8dbc-dbe9006e9752/S1_021606_IW3_20210114_20210126_VV_INT80_8390.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/f5a5cf88-0d67-488f-98ba-4703cb711bd4/S1_021606_IW3_20210420_20210514_VV_INT80_E579.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/3d052ee8-8f49-4196-922b-2b3bb2d2a387/S1_021606_IW3_20210408_20210502_VV_INT80_A148.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/ffc674d2-d539-41f1-9bc2-1e75b17d2105/S1_021606_IW3_20201221_20210114_VV_INT80_DD9A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4099bd64-30aa-43a8-b1b3-940ec1dd7433/S1_021606_IW3_20210408_20210420_VV_INT80_2C81.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/f22f65ff-6edd-4ebd-9813-534b3dba72cb/S1_021606_IW3_20210514_20210526_VV_INT80_A01B.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4fb084c7-4dcc-4566-9ff8-a9bcc7a0ea79/S1_021606_IW3_20210207_20210303_VV_INT80_2731.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/5693ad35-5079-41f6-8662-7f65fbf2a16f/S1_021606_IW3_20210327_20210408_VV_INT80_885E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/da36bd8e-86ef-46f2-a63c-bf382d921eef/S1_021606_IW3_20201209_20210102_VV_INT80_0FCC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4add01b2-a502-4250-b93e-ec92c999717e/S1_021606_IW3_20200928_20201022_VV_INT80_E93F.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/06512671-a495-4c6e-8ad4-a1e2578da646/S1_021606_IW3_20200718_20200730_VV_INT80_8670.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/cf0280ad-8723-457c-adb6-1c617cc0c31c/S1_021606_IW3_20200811_20200823_VV_INT80_0464.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b3438e37-fd4f-4efc-9ff0-3ae69f4ee9b1/S1_021606_IW3_20200612_20200624_VV_INT80_9238.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/dee451e2-c176-49a6-a0ec-5332549b9269/S1_021606_IW3_20200730_20200811_VV_INT80_67AD.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/2216d40e-4ef0-4c79-83ca-c1c369fc4aa2/S1_021606_IW3_20200624_20200706_VV_INT80_35AD.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4e336ae9-5a35-41e8-9ff0-3c1287f9ab3a/S1_021606_IW3_20200531_20200612_VV_INT80_508A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/5fdf213a-3bbb-44bf-80ad-0a8691d3efc6/S1_021606_IW3_20200928_20201010_VV_INT80_DE46.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/3dad52ef-8853-48a3-8846-a22eac29416f/S1_021606_IW3_20200904_20200928_VV_INT80_2EDF.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/95354c81-e3c5-40e0-bd86-342657fa420b/S1_021606_IW3_20200823_20200916_VV_INT80_40B5.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/98f05a4c-25e1-4e5e-a9c4-fe579f3ecb07/S1_021606_IW3_20200706_20200718_VV_INT80_C122.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/e1f4f20a-d1e9-47fa-8b2c-022370ba103b/S1_021606_IW3_20200916_20200928_VV_INT80_91AC.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/ca7260bb-0a16-4cd0-8540-a904440a5ef5/S1_021606_IW3_20200718_20200811_VV_INT80_942E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/c108e72a-8b23-4d1d-a877-b6f2f2ce2702/S1_021606_IW3_20200612_20200706_VV_INT80_F636.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/a387879a-306d-4138-a4ee-a2ab9d145fbb/S1_021606_IW3_20200531_20200624_VV_INT80_BFF4.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/99b10326-20f6-4d9c-aad5-51f6a2add225/S1_021606_IW3_20200904_20200916_VV_INT80_2358.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/3c0e17cd-e341-4842-844d-d662e078c0e8/S1_021606_IW3_20200730_20200823_VV_INT80_8E22.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b7ff545c-0033-42d9-97ed-49ea60c52c54/S1_021606_IW3_20200823_20200904_VV_INT80_E3ED.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/82b482af-fc2c-4be9-8265-3fec9ccbb25a/S1_021606_IW3_20200624_20200718_VV_INT80_D290.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b3ee0de4-03fe-46fb-a82d-3b35a07d9ec5/S1_021606_IW3_20200811_20200904_VV_INT80_C7A8.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/6c9a9d6f-650a-4382-a8df-3b72fb7fd4bc/S1_021606_IW3_20200916_20201010_VV_INT80_DC3A.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/ba84d71a-823c-4354-9a46-581edd7522fc/S1_021606_IW3_20200213_20200225_VV_INT80_CDC6.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/1841b096-e0f1-4638-a174-13452f3156b1/S1_021606_IW3_20200320_20200401_VV_INT80_39B0.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/3aa9f7d7-80d9-4d5b-905b-104c61799f75/S1_021606_IW3_20200320_20200413_VV_INT80_CD6E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/8b85b1a3-a751-4190-a03b-68e8da4af192/S1_021606_IW3_20200201_20200225_VV_INT80_3958.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/2196e6f2-e9df-474b-bf88-c21f72662739/S1_021606_IW3_20200308_20200320_VV_INT80_7FE2.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/5c7a71d2-2af0-497f-8789-a5f51b4b4459/S1_021606_IW3_20200108_20200201_VV_INT80_9F89.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/9629c822-3cac-451c-aa7e-4613ecbad709/S1_021606_IW3_20200413_20200425_VV_INT80_7CDD.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/9fe9b188-2281-4615-81ff-b438b67141ed/S1_021606_IW3_20200225_20200308_VV_INT80_9E4F.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/b0a587e1-26c2-47e1-91c7-9f234a06039c/S1_021606_IW3_20200308_20200401_VV_INT80_53EB.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/1a5f45ab-437b-4ff0-9682-79d520e46602/S1_021606_IW3_20200225_20200320_VV_INT80_9E3E.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/1cea197d-94f1-4540-87b3-7ad191e2ba95/S1_021606_IW3_20200201_20200213_VV_INT80_52B9.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/6cb8398c-24c1-4e4d-904b-07a0fe2fc78b/S1_021606_IW3_20200507_20200531_VV_INT80_8AC5.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/21c6a640-28a9-45bd-a1f6-4e2776a4080a/S1_021606_IW3_20200213_20200308_VV_INT80_48C3.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/a9900992-6ec0-43f7-b9d6-53ca4d96f17d/S1_021606_IW3_20200120_20200213_VV_INT80_9930.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/531ebd63-77bb-4e9a-a6d0-892d76fad086/S1_021606_IW3_20200425_20200507_VV_INT80_7F43.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/8f0df55b-1592-4e0d-8e3b-7c6abff888b0/S1_021606_IW3_20200401_20200425_VV_INT80_22E7.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/38126dfa-d36f-4a32-a293-6fa3221af94f/S1_021606_IW3_20200120_20200201_VV_INT80_89A2.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/36d16512-59c9-4370-8b1e-035af496597b/S1_021606_IW3_20200413_20200507_VV_INT80_54BF.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/4d0cc4fa-528f-497c-b3f2-07a73079f7fd/S1_021606_IW3_20200401_20200413_VV_INT80_54AD.zip",
                       "https://d3gm2hf49xd6jj.cloudfront.net/fe8b26c0-17e8-4448-ae9e-476bf46060f4/S1_021606_IW3_20200108_20200120_VV_INT80_BE1E.zip" ]

        # Local stash of cookies so we don't always have to ask
        self.cookie_jar_path = os.path.join(
                os.path.expanduser('~'),
                ".bulk_download_cookiejar.txt"
                )
        self.cookie_jar = None

        self.asf_urs4 = { 'url': 'https://urs.earthdata.nasa.gov/oauth/authorize',
                         'client': 'BO_n7nTIlMljdvU6kRRB3g',
                         'redir': 'https://auth.asf.alaska.edu/login'}

        # Make sure we can write it our current directory
        if os.access(os.getcwd(), os.W_OK) is False:
            print(f"WARNING: Cannot write to current path! Check permissions for {os.getcwd()}")
            exit(-1)

        # For SSL
        self.context = {}

        # Check if user handed in a Metalink or CSV:
        if len(sys.argv) > 0:
            download_files = []
            input_files = []
            for arg in sys.argv[1:]:
                if arg == '--insecure':
                    try:
                        ctx = ssl.create_default_context()
                        ctx.check_hostname = False
                        ctx.verify_mode = ssl.CERT_NONE
                        self.context['context'] = ctx
                    except AttributeError:
                        # Python 2.6 won't complain about SSL Validation
                        pass

                elif arg.endswith('.metalink') or arg.endswith('.csv'):
                    if os.path.isfile(arg):
                        input_files.append(arg)
                        if arg.endswith('.metalink'):
                            new_files = self.process_metalink(arg)
                        else:
                            new_files = self.process_csv(arg)
                        if new_files is not None:
                            for file_url in (new_files):
                                download_files.append(file_url)
                    else:
                        print(f" > I cannot find the input file you specified: {arg}")
                else:
                    print(f" > Command line argument '{arg}' makes no sense, ignoring.")

            if len(input_files) > 0:
                if len(download_files) > 0:
                    print(f" > Processing {len(download_files)} downloads from {len(input_files)} input files. ")
                    self.files = download_files
                else:
                    print(f" > I see you asked me to download files from {len(input_files)} input files, but they had no downloads!")
                    print(" > I'm super confused and exiting.")
                    exit(-1)

        # Make sure cookie_jar is good to go!
        self.get_cookie()

        # summary
        self.total_bytes = 0
        self.total_time = 0
        self.cnt = 0
        self.success = []
        self.failed = []
        self.skipped = []

    # Get and validate a cookie
    def get_cookie(self):
        if os.path.isfile(self.cookie_jar_path):
            self.cookie_jar = MozillaCookieJar()
            self.cookie_jar.load(self.cookie_jar_path)

            if self.check_cookie():
                print(" > Reusing previous cookie jar.")
                return
            else:
                print(" > Could not validate old cookie Jar")

        # We don't have a valid cookie, prompt user or creds
        print("No existing URS cookie found, please enter Earthdata username & password:")
        print("(Credentials will not be stored, saved or logged anywhere)")

        # Keep trying 'till user gets the right U:P
        while self.check_cookie() is False:
            self.get_new_cookie()

    # Validate cookie before we begin
    def check_cookie(self):
        if self.cookie_jar is None:
            print(f" > Cookiejar is bunk: {self.cookie_jar}")
            return False

        # File we know is valid, used to validate cookie
        file_check = 'https://urs.earthdata.nasa.gov/profile'

        # Apply custom Redirect Hanlder
        opener = build_opener(
            HTTPCookieProcessor(self.cookie_jar),
            HTTPHandler(),
            HTTPSHandler(**self.context)
        )
        install_opener(opener)

        # Attempt a HEAD request
        request = Request(file_check)
        request.get_method = lambda : 'HEAD'
        try:
            print(f" > attempting to download {file_check}")
            response = urlopen(request, timeout=30)
            resp_code = response.getcode()
            # Make sure we're logged in
            if not self.check_cookie_is_logged_in(self.cookie_jar):
                return False

            # Save cookiejar
            self.cookie_jar.save(self.cookie_jar_path)

        except HTTPError:
            # If we ge this error, again, it likely means the user has not agreed to current EULA
            print("\nIMPORTANT: ")
            print("Your user appears to lack permissions to download data from the ASF Datapool.")
            print("\n\nNew users: you must first log into Vertex and accept the EULA. In addition, your Study Area must be set at Earthdata https://urs.earthdata.nasa.gov")
            exit(-1)

        # This return codes indicate the USER has not been approved to download the data
        if resp_code in (300, 301, 302, 303):
            try:
                redir_url = response.info().getheader('Location')
            except AttributeError:
                redir_url = response.getheader('Location')

            # Funky Test env:
            if ("vertex-retired.daac.asf.alaska.edu" in redir_url and "test" in self.asf_urs4['redir']):
                print("Cough, cough. It's dusty in this test env!")
                return True

            print(f"Redirect ({resp_code}) occured, invalid cookie value!")
            return False

        # These are successes!
        if resp_code in (200, 307):
            return True
        else:
            return False

    def get_new_cookie(self):
        # Start by prompting user to input their credentials

        new_username = input("Username: ")
        new_password = getpass.getpass(prompt="Password (will not be displayed): ")

        # Build URS4 Cookie request
        auth_cookie_url = self.asf_urs4['url'] + '?client_id=' + self.asf_urs4['client'] + '&redirect_uri=' + self.asf_urs4['redir'] + '&response_type=code&state='

        user_pass = base64.b64encode(bytes(new_username+":"+new_password, "utf-8"))
        user_pass = user_pass.decode("utf-8")

        # Authenticate against URS, grab all the cookies
        self.cookie_jar = MozillaCookieJar()
        opener = build_opener(HTTPCookieProcessor(self.cookie_jar), HTTPHandler(), HTTPSHandler(**self.context))
        request = Request(auth_cookie_url, headers={"Authorization": "Basic {0}".format(user_pass)})

        # Watch out cookie rejection!
        try:
            response = opener.open(request)
        except HTTPError as e:
            if "WWW-Authenticate" in e.headers and "Please enter your Earthdata Login credentials" in e.headers["WWW-Authenticate"]:
                print(" > Username and Password combo was not successful. Please try again.")
                return False
            else:
                # If an error happens here, the user most likely has not confirmed EULA.
                print("\nIMPORTANT: There was an error obtaining a download cookie!")
                print("Your user appears to lack permission to download data from the ASF Datapool.")
                print("\n\nNew users: you must first log into Vertex and accept the EULA. In addition, your Study Area must be set at Earthdata https://urs.earthdata.nasa.gov")
                exit(-1)
        except URLError as e:
            print("\nIMPORTANT: There was a problem communicating with URS, unable to obtain cookie. ")
            print("Try cookie generation later.")
            exit(-1)

        # Did we get a cookie?
        if self.check_cookie_is_logged_in(self.cookie_jar):
            self.cookie_jar.save(self.cookie_jar_path)
            return True

        # if we aren't successful generating the cookie, nothing will work. Stop here!
        print("WARNING: Could not generate new cookie! Cannot proceed. Please try Username and Password again.")
        print("Response was {response.getcode()}.")
        print("\n\nNew users: you must first log into Vertex and accept the EULA. In addition, your Study Area must be set at Earthdata https://urs.earthdata.nasa.gov")
        exit(-1)

    # make sure we're logged into URS
    def check_cookie_is_logged_in(self, cj):
        for cookie in cj:
            if cookie.name in ['urs_user_already_logged', 'asf-urs']:
                # Only get this cookie if we logged in successfully!
                return True

        return False

    def confirm_authentication(self, request: Request, url: str):
        parsed_url = urlparse(url)
        # list of others urls to add authentication to
        if parsed_url.hostname in ['cumulus.asf.earthdatacloud.nasa.gov', 'nisar.asf.earthdatacloud.nasa.gov' ]:
            for cookie in self.cookie_jar:
                if cookie.name == 'urs-access-token':
                    request.add_header('Authorization', 'Bearer ' + cookie.value)
                    break

    # Download the file
    def download_file_with_cookiejar(self, url, file_count, total, recursion=False):
        # see if we've already download this file and if it is that it is the correct size
        download_file = os.path.basename(url).split('?')[0]

        # Check if the file already exists and is the correct size
        # TODO: make this a function delete_partial_download
        if os.path.isfile(download_file):
            try:
                request = Request(url)
                # request.get_method = lambda : 'HEAD'
                self.confirm_authentication(request, url)
                local_size = os.path.getsize(download_file) if os.path.isfile(download_file) else 'N/A'
                remote_size = self.get_total_size(urlopen(request)) if not recursion else 'N/A'
                if local_size != 'N/A' and remote_size != 'N/A':
                    if (local_size + (local_size * .01)) > remote_size > (
                            local_size - (local_size * .01)):
                        print(f" > Download file {download_file} exists! \n > Skipping download of {url}. ")
                        return None, None
                    # partial file size wasn't full file size, lets blow away the chunk and start again
                    print(
                        f" > Found {download_file} but it wasn't fully downloaded. Removing file and downloading again.")
                    os.remove(download_file)

            except ssl.CertificateError as e:
                print(f" > ERROR: {e}")
                print(" > Could not validate SSL Cert. You may be able to overcome this using the --insecure flag")
                return False, None

            except HTTPError as e:
                if e.code == 401:
                    print(" > IMPORTANT: Your user may not have permission to download this type of data!")
                else:
                    print(" > Unknown Error, Could not get file HEAD: {0}".format(e))

            except URLError as e:
                print("URL Error (from HEAD): {0}, {1}".format( e.reason, url))
                if "ssl.c" in "{0}".format(e.reason):
                    print("IMPORTANT: Remote location may not be accepting your SSL configuration. This is a terminal error.")
                return False, None

        # attempt https connection
        try:
            request = Request(url)
            self.confirm_authentication(request, url)
            response = urlopen(request, timeout=30)

            while response.getcode() == 202:
                print(" > Waiting for burst extraction service...")
                time.sleep(5)
                response = urlopen(request, timeout=30)

            # Watch for redirect
            if response.geturl() != url:

                # See if we were redirect BACK to URS for re-auth.
                if 'https://urs.earthdata.nasa.gov/oauth/authorize' in response.geturl():
                    if recursion:
                        print(" > Entering seemingly endless auth loop. Aborting. ")
                        return False, None

                    # make this easier. If there is no app_type=401, add it
                    new_auth_url = response.geturl()
                    if "app_type" not in new_auth_url:
                        new_auth_url += "&app_type=401"

                    print(f" > While attempting to download {url}....")
                    print(f" > Need to obtain new cookie from {new_auth_url}")
                    old_cookies = [cookie.name for cookie in self.cookie_jar]
                    opener = build_opener(HTTPCookieProcessor(self.cookie_jar), HTTPHandler(), HTTPSHandler(**self.context))
                    request = Request(new_auth_url)
                    try:
                        response = opener.open(request)
                        for cookie in self.cookie_jar:
                            if cookie.name not in old_cookies:
                                print(" > Saved new cookie: {0}".format(cookie.name))

                                # A little hack to save session cookies
                                if cookie.discard:
                                    cookie.expires = int(time.time()) + 60*60*24*30
                                    print(" > Saving session Cookie that should have been discarded! ")

                        self.cookie_jar.save(self.cookie_jar_path, ignore_discard=True, ignore_expires=True)
                    except HTTPError as e:
                        print(f"HTTP Error: {e.code}, {url}")
                        return False, None

                    # Okay, now we have more cookies! Lets try again, recursively!
                    print(" > Attempting download again with new cookies!")
                    return self.download_file_with_cookiejar(url, file_count, total, recursion=True)

                print(f" > 'Temporary' Redirect download @ Remote archive:\n > {response.geturl()}")

            # seems to be working
            print(f"({file_count}/{total}) Downloading {url}")

            content_disposition = response.headers.get('Content-Disposition')

            if content_disposition and len(content_disposition):
                possible_filename = re.findall(r"filename=(\S+)", content_disposition)

                if possible_filename:
                    download_file = possible_filename.pop()

            # Open our local file for writing and build status bar
            tf = tempfile.NamedTemporaryFile(mode='w+b', delete=False, dir='.')
            self.chunk_read(response, tf, report_hook=self.chunk_report)

            # Reset download status
            sys.stdout.write('\n')

            tempfile_name = tf.name
            tf.close()

        except HTTPError as e:
            print(f"HTTP Error: {e.code}, {url}")

            if e.code == 401:
                print(" > IMPORTANT: Your user does not have permission to download this type of data!")

            if e.code == 403:
                print(" > Got a 403 Error trying to download this file.  ")
                print(" > You MAY need to log in this app and agree to a EULA. ")

            return False, None

        except URLError as e:
            print("URL Error (from GET): {0}, {1}, {2}".format(e, e.reason, url))

            if "ssl.c" in "{0}".format(e.reason):
                print("IMPORTANT: Remote location may not be accepting your SSL configuration. This is a terminal error.")

            return False, None

        except socket.timeout as e:
            print(f" > timeout requesting: {url}; {e}")
            return False, None

        except ssl.CertificateError as e:
            print(f" > ERROR: {e}")
            print(" > Could not validate SSL Cert. You may be able to overcome this using the --insecure flag")
            return False, None

        # Return the file size
        shutil.copy(tempfile_name, download_file)
        os.remove(tempfile_name)
        file_size = self.get_total_size(response)
        actual_size = os.path.getsize(download_file)
        if file_size is None:
            # We were unable to calculate file size.
            file_size = actual_size

        return actual_size, file_size

    def get_redirect_url_from_error(self, error):
        find_redirect = re.compile(r"id=\"redir_link\"\s+href=\"(\S+)\"")
        print(f"error file was: {error}")
        redirect_url = find_redirect.search(error)

        if redirect_url:
            print(f"Found: {redirect_url.group(0)}")
            return (redirect_url.group(0))

        return None

    #  chunk_report taken from http://stackoverflow.com/questions/2028517/python-urllib2-progress-hook
    def chunk_report(self, bytes_so_far, file_size):
        if file_size is not None:
            percent = float(bytes_so_far) / file_size
            percent = round(percent*100, 2)
            sys.stdout.write(f" > Downloaded {bytes_so_far} of {file_size} bytes ({percent:0.2f}%)\r")
        else:
            # We couldn't figure out the size.
            sys.stdout.write(f" > Downloaded {bytes_so_far} of unknown Size\r")

    #  chunk_read modified from http://stackoverflow.com/questions/2028517/python-urllib2-progress-hook
    def chunk_read(self, response, local_file, chunk_size=8192, report_hook=None):
        file_size = self.get_total_size(response)
        bytes_so_far = 0

        while 1:
            try:
                chunk = response.read(chunk_size)
            except Exception:
                sys.stdout.write("\n > There was an error reading data. \n")
                break

            try:
                local_file.write(chunk)
            except TypeError:
                local_file.write(chunk.decode(local_file.encoding))
            bytes_so_far += len(chunk)

            if not chunk:
                break

            if report_hook:
                report_hook(bytes_so_far, file_size)

        return bytes_so_far

    def get_total_size(self, response):
        try:
            file_size = response.info().getheader('Content-Length').strip()
        except AttributeError:
            try:
                file_size = response.getheader('Content-Length').strip()
            except AttributeError:
                print("> Problem getting size")
                return None

        return int(file_size)

    # Get download urls from a metalink file
    def process_metalink(self, ml_file):
        print(f"Processing metalink file: {ml_file}")
        with open(ml_file, 'r') as ml:
            xml = ml.read()

        # Hack to remove annoying namespace
        it = ET.iterparse(StringIO(xml))
        for _, el in it:
            if '}' in el.tag:
                el.tag = el.tag.split('}', 1)[1]  # strip all namespaces
        root = it.root

        dl_urls = []
        ml_files = root.find('files')
        for dl in ml_files:
            dl_urls.append(dl.find('resources').find('url').text)

        if len(dl_urls) > 0:
            return dl_urls
        else:
            return None

    # Get download urls from a csv file
    def process_csv(self, csv_file):
        print(f"Processing csv file: {csv_file}")

        dl_urls = []
        with open(csv_file, 'r') as csvf:
            try:
                csvr = csv.DictReader(csvf)
                for row in csvr:
                    dl_urls.append(row['URL'])
            except csv.Error as e:
                print(f"WARNING: Could not parse file {csv_file}, line {csvr.line_num}: {e}. Skipping.")
                return None
            except KeyError:
                print(f"WARNING: Could not find URL column in file {csv_file}. Skipping.")

        if len(dl_urls) > 0:
            return dl_urls
        else:
            return None

    # Download all the files in the list
    def download_files(self):
        for file_name in self.files:

            # make sure we haven't ctrl+c'd or some other abort trap
            if abort is True:
                raise SystemExit

            # download counter
            self.cnt += 1

            # set a timer
            start = time.time()

            # run download
            size, total_size = self.download_file_with_cookiejar(file_name, self.cnt, len(self.files))

            # calculte rate
            end = time.time()

            # stats:
            if size is None:
                self.skipped.append(file_name)

            elif self.is_good_download(total_size, size):
                elapsed = end - start
                elapsed = 1.0 if elapsed < 1 else elapsed
                rate = (size/1024**2)/elapsed

                print(f"Downloaded {size}b in {elapsed:.2f}secs, Average Rate: {rate:.2f}MB/sec")

                # add up metrics
                self.total_bytes += size
                self.total_time += elapsed
                self.success.append({'file': file_name, 'size': size })

            else:
                print(f"There was a problem downloading {file_name}")
                self.failed.append(file_name)

    def is_good_download(self, total_size, size):
        return (
            size is not False and
            (
                total_size < (size+(size*.01)) and
                total_size > (size-(size*.01))
            )
        )

    def print_summary(self):
        # printsummary:
        print("\n\nDownload Summary ")
        print("--------------------------------------------------------------------------------")
        print(f"  Successes: {len(self.success)} files, {self.total_bytes} bytes ")
        for success_file in self.success:
            size_mb = success_file['size']/1024.0**2
            print(f"           - {success_file['file']}  {size_mb:.2f}MB")

        if len(self.failed) > 0:
            print(f"  Failures: {len(self.failed)} files")
            for failed_file in self.failed:
                print(f"          - {failed_file}")

        if len(self.skipped) > 0:
            print(f"  Skipped: {len(self.skipped)} files")
            for skipped_file in self.skipped:
                print("          - {0}".format(skipped_file))

        if len(self.success) > 0:
            total_bytes_mb = self.total_bytes/1024.0**2
            download_rate = total_bytes_mb / self.total_time
            print(f"  Average Rate: {download_rate:.2f}MB/sec")

        print("--------------------------------------------------------------------------------")


if __name__ == "__main__":
    # Setup a signal trap for SIGINT (Ctrl+C)
    signal.signal(signal.SIGINT, signal_handler)

    downloader = bulk_downloader()
    downloader.download_files()
    downloader.print_summary()
