// AUTO-GENERATED by cracks/gen_road_cracks.py - do not edit by hand.
// Mock road-crack detections placed at the highest InSAR subsidence-
// gradient locations (differential settlement = pavement-crack driver).
// Heatmap thumbnails are real outputs of the asphalt crack model.

export interface RoadCrack {
  id: string;
  lat: number;
  lng: number;
  district: string;
  severity: 'Low' | 'Moderate' | 'High' | 'Severe';
  crackType: string;
  lengthM: number;
  widthMm: number;
  confidence: number;
  detectedAt: string;
  heatmap: string;
  subsidenceGradientScore: number;
  subsidenceVelocityMmYr: number;
  nearestBlockRisk: number;
  crackTilePct: number;
}

export const ROAD_CRACKS: RoadCrack[] = [
  {
    "id": "crack-1",
    "lat": 22.282328,
    "lng": 114.129193,
    "district": "Central & Western",
    "severity": "Severe",
    "crackType": "Alligator",
    "lengthM": 34.9,
    "widthMm": 40.0,
    "confidence": 1.0,
    "detectedAt": "2026-05-18",
    "heatmap": "/cracks/crack_1.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": -72.2,
    "nearestBlockRisk": 82.6,
    "crackTilePct": 27.3
  },
  {
    "id": "crack-2",
    "lat": 22.278079,
    "lng": 114.22859,
    "district": "Eastern",
    "severity": "High",
    "crackType": "Longitudinal",
    "lengthM": 22.6,
    "widthMm": 24.6,
    "confidence": 0.999,
    "detectedAt": "2026-05-21",
    "heatmap": "/cracks/crack_2.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": -24.0,
    "nearestBlockRisk": 37.3,
    "crackTilePct": 22.5
  },
  {
    "id": "crack-3",
    "lat": 22.277868,
    "lng": 114.237382,
    "district": "Eastern",
    "severity": "Moderate",
    "crackType": "Transverse",
    "lengthM": 22.5,
    "widthMm": 8.6,
    "confidence": 1.0,
    "detectedAt": "2026-05-24",
    "heatmap": "/cracks/crack_3.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": -6.2,
    "nearestBlockRisk": 47.1,
    "crackTilePct": 26.8
  },
  {
    "id": "crack-4",
    "lat": 22.277918,
    "lng": 114.237913,
    "district": "Eastern",
    "severity": "Moderate",
    "crackType": "Block",
    "lengthM": 29.5,
    "widthMm": 8.6,
    "confidence": 0.999,
    "detectedAt": "2026-05-27",
    "heatmap": "/cracks/crack_4.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": -6.2,
    "nearestBlockRisk": 47.1,
    "crackTilePct": 26.8
  },
  {
    "id": "crack-5",
    "lat": 22.325825,
    "lng": 114.17459,
    "district": "Kowloon City",
    "severity": "Moderate",
    "crackType": "Pothole edge",
    "lengthM": 36.4,
    "widthMm": 8.5,
    "confidence": 0.97,
    "detectedAt": "2026-05-30",
    "heatmap": "/cracks/crack_5.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": 6.1,
    "nearestBlockRisk": 83.7,
    "crackTilePct": 22.5
  },
  {
    "id": "crack-6",
    "lat": 22.311835,
    "lng": 114.187022,
    "district": "Kowloon City",
    "severity": "Severe",
    "crackType": "Alligator",
    "lengthM": 17.9,
    "widthMm": 29.7,
    "confidence": 1.0,
    "detectedAt": "2026-06-02",
    "heatmap": "/cracks/crack_6.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": -29.7,
    "nearestBlockRisk": 91.8,
    "crackTilePct": 26.8
  },
  {
    "id": "crack-7",
    "lat": 22.31867,
    "lng": 114.17399,
    "district": "Kowloon City",
    "severity": "High",
    "crackType": "Longitudinal",
    "lengthM": 22.0,
    "widthMm": 23.3,
    "confidence": 1.0,
    "detectedAt": "2026-06-03",
    "heatmap": "/cracks/crack_7.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": 22.6,
    "nearestBlockRisk": 57.3,
    "crackTilePct": 21.6
  },
  {
    "id": "crack-8",
    "lat": 22.328795,
    "lng": 114.207593,
    "district": "Kwun Tong",
    "severity": "Moderate",
    "crackType": "Transverse",
    "lengthM": 22.5,
    "widthMm": 8.6,
    "confidence": 1.0,
    "detectedAt": "2026-06-04",
    "heatmap": "/cracks/crack_8.jpg",
    "subsidenceGradientScore": 100.0,
    "subsidenceVelocityMmYr": 6.2,
    "nearestBlockRisk": 38.1,
    "crackTilePct": 26.0
  }
];
